services:
  db:
    image: postgres:15
    container_name: postgres_db2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: recargapaydb
    ports:
      - "5432:5432"
    volumes:
      - ./src/test/resources/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - pgnet

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - pgnet

networks:
  pgnet:
